### ISSUE TITLE
Edit repository details and other niceties

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/front#100]
**Is your feature request related to a problem? Please describe.**
Front repository has no __Github__ description.

**Describe the solution you'd like**
- [x] Set a repository description
- [x] Set a repository website
- [x] Set repository topics
- [x] Social preview : Upload an image to customize your repository’s social media preview.

**Comment by aangelot** [comment]
@lutangar I just added description, website, topic and social preview for this repo. Tell me if it fits Github practices

**Comment by lutangar** [comment]
:rainbow: Wonderful ! 

Here's a few suggestions for the description :

Instead of 

> DatAtlas front : create custom maps front by choosing data, style and map features

Why not

> :world_map: DatAtlas front : create maps with custom data, style and features.

Or 

> :world_map: DatAtlas frontend is an interface to create maps with custom data, style and features.

Or 

> :world_map: [front] DatAtlas is an interface to create maps website with custom data, style and features.


Mix and match with whatever words feels more appropriate in our case.
