### ISSUE TITLE
Customize organization's profile

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/front#101]
**Is your feature request related to a problem? Please describe.**
There is no description nor link to the __Datatlas__ page nor project(s).
How the project is funded isn't describe anywhere.

**Describe the solution you'd like**

> :warning: All suggestions might not be relevant in our case.

- [x] Link to https://www.erasme.org/DatAtlas from __Github__ [__Datatlas__ organization page](https://github.com/datatlas-erasme)
- [x] Create an [organization wide README](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile) 

[Set guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
- [x] CODE_OF_CONDUCT.md *This might be important and you might have meaningful values to expose to the rest of the world*
- [ ] CONTRIBUTING.md *might be premature*
- [ ] FUNDING.yml  *This one matter since there is public money involved*
- [ ] SECURITY.md *Don't know if relevant here*
- [x] SUPPORT.md

**Comment by aangelot** [comment]
Hi @lutangar ! 
Can you look at the organization readme, code of conduct and support files to tell me if they are ok ? 
For the other files : 

- contributing : why not write it right now ? But we have to do this together
- funding : Github says "A FUNDING file displays a sponsor button in your repository to increase the visibility of funding options for your open source project." Not sur we want to be funded, if it's juste to say the project is developed thanks to public money, I added it on the organization readme
- security : we will have to do add this file, may be premature today

**Comment by lutangar** [comment]
Great work ! 

Let's schedule a documentation jam sometimes on a few [collaborative markdown pads](https://hedgedoc.org/) to finalize the last details.
