### ISSUE TITLE
Problem with "noImplicitUseStrict" in .tsconfig.json

### ISSUE THREAD

**Issue by OlivPi** [datatlas-erasme/front#105]
[**Describe the bug**
Disable adding 'use strict' directives in emitted JavaScript files.
Option 'noImplicitUseStrict' cannot be specified with option 'alwaysStrict'.ts

**Expected behavior**
It's look like a local bug. Please could have any solution about this ?

**Comment by Pipazoul** [comment]
> [**Describe the bug** Disable adding 'use strict' directives in emitted JavaScript files. Option 'noImplicitUseStrict' cannot be specified with option 'alwaysStrict'.ts
> 
> **Expected behavior** It's look like a local bug. Please could have any solution about this ?

Does it block you in any way ?

It seems to be a warning inviting you to remove the `"noImplicitUseStrict": true,` section, because `"strict": true,`  param overrides  the other strict params ?

**Comment by OlivPi** [comment]
I have just a warning about this param, nothing more, i just would to close it.

If i remove `"noImplicitUseStrict": true` , my next "push" will failed.

**Comment by lutangar** [comment]
Hey @OlivPi does the problem occurs on `dev` or solely on your branch `dev-opendata-alimentaire` ?
Feel free to ask for help to merge `dev` with your branche, configuration have been moved around lately, so there might be a few misplaced configuration files.

**Comment by OlivPi** [comment]
Hey @lutangar ,

The problem occurs in both branchs.

Yes, i would like some help from merge the branch and apply the new configuration on dev-opendata-alimentaire.

Thanks

**Comment by OlivPi** [comment]
UPDATE

There are always the bug after the merge... It's could be come from my computer/vscode environment ?
