### ISSUE TITLE
Husky giving me hard times on a Dockerfile

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#106]
### Discussed in https://github.com/datatlas-erasme/front/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **Pipazoul** August  4, 2022</sup>
While trying to commit my new version of a Dockerfile the pre-commit integration stops me from commiting annoucing me 
``` bash
[91m[91m×[91m eslint --fix:[39m
[0m[0m
[0m[4mC:\path\to\datatlas\front\Dockerfile[24m[0m
[0m  [2m2:4[22m  [31merror[39m  Parsing error: Missing semicolon. (2:4)[0m
[0m[0m
[0m[31m[1m✖ 1 problem (1 error, 0 warnings)[22m[39m[0m
[0m[31m[1m[22m[39m[0m
husky - pre-commit hook exited with code 1 (error)
```

I've tried to ignore the docker file with an .eslintignore but no change</div>

**Comment by lutangar** [comment]
Ping @Pipazoul https://github.com/datatlas-erasme/front/pull/109
