### ISSUE TITLE
Be able to choose in wich order the filters for each layer are displayed

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#119]
**Is your feature request related to a problem? Please describe.**
When the data is loaded into the front the order of filters display is based on the the time each data loads 

**Describe the solution you'd like**
Be able the define the display order of filter trought the instance config

**Comment by aangelot** [comment]
Should be ok on dev

**Comment by Pipazoul** [comment]
Checked on dev it works
