### ISSUE TITLE
New logos in the header

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#149]
In the header : 

Replace the logo of the Metropole of lyon with the new one (https://www.lyonmag.com/media/images/6314c50d25e5d-metropole-grand-lyon-logo-1.png) 

Add bellebouffe logo : https://auvergne-rhone-alpes.ambition-ess.org/sites/default/files/styles/large/public/2021-06/images/logo/bellebouffe-logo.png?itok=Ty2BjQyB

**Comment by OlivPi** [comment]
@OlivPi
[STYLE: Add new Logo Metropole & BelleBouffe](https://github.com/datatlas-erasme/front/pull/134/commits/9ad90cccbed1ad24caf6d63fdcbf361663d3d4d7)
[9ad90cc](https://github.com/datatlas-erasme/front/pull/134/commits/9ad90cccbed1ad24caf6d63fdcbf361663d3d4d7)
