### ISSUE TITLE
Cannot close the "Who" filters on small computer screens 

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#169]
**Describe the bug**
![image](https://user-images.githubusercontent.com/33604381/194526827-f41c0652-869f-40be-bbf8-f1eb50a4fdf8.png)

**To Reproduce**
Reduce the size of your window 

**Expected behavior**
Make it responsive (taking in account the header

**Comment by OlivPi** [comment]
@aangelot , could you give me the device résolutions ?
