### ISSUE TITLE
Search engine (title or description based) 

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#18]
**Is your feature request related to a problem? Please describe.**
I want to easily find a point on the map, knowing only the title or the description. 

**Describe the solution you'd like**
I'd like to have a seach bar in which I can write what I'm looking for. DatAtlas will dynamically only show me the POI containing my text

**Additional context**
The seach fields (title, description, etc.) can be determined by the admin at the map init

**Comment by aangelot** [comment]
Design required

**Comment by lutangar** [comment]
> Will be implemented in __Datatlas__ https://github.com/datatlas-erasme/datatlas/issues/172
