### ISSUE TITLE
Modular notion backend

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#24]
**Is your feature request related to a problem? Please describe.**
For now the notion tables requested by the back are pre-maped, for every new table the fileds need to beed coded into the back

**Describe the solution you'd like**

The backshould be able to request a notion table and convert it into kepler.gl format by himself

Some guideline on creating notion tables will also bee needed (collumn/namin - type of column compatible / and so on ...)

**Comment by racine-p-a** [comment]
@Pipazoul Have you tested the new dev branch about this issue ? In that case and if it besuits you, i'll let you close the issue. If not, tell me what is missing.
