### ISSUE TITLE
Add a button to see the data tables

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#32]
**Describe the solution you'd like**
A button under the crowdsourcing button 
On click the button would display keplers tableview modal

The button visibility should be dedined in a conf gile

**Comment by Pipazoul** [comment]
@aangelot is this still a need for the next release or can it be skipped until some user feedback validates it ?

**Comment by aangelot** [comment]
@Pipazoul it still a need, but clear not the most important for the 0.5 

Is this issue different from https://github.com/datatlas-erasme/front/issues/22 ?
