### ISSUE TITLE
Buttons Styling

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#37]
A. we stay vertical but we reactivate the scroll-bar (with a small padding on the right of ±15px), and we add the extra buttons (add a layer, a place, event, list mode, about...) directly under the filter buttons.
B. Sub-filters: if possible vertical space ok for 2 lines for all. All same vertical height.
C. Vertical space between layer buttons variable: close (±4px) when all are closed, larger around those that are open (±10-15px)

**Comment by Pipazoul** [comment]
TODO FIx the { adding space between child filter buttons
