### ISSUE TITLE
Default map centring

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#38]
**Is your feature request related to a problem? Please describe.**
Because of a data at Montreal, the map is centered on the Atlantic Ocean... which isn't the most interesting place for industrial mediation 

**Describe the solution you'd like**
Center by default the map like in the screenshot below 

**Additional context**
<img width="1413" alt="Capture d’écran 2021-12-07 à 17 05 59" src="https://user-images.githubusercontent.com/33604381/145075788-994962f1-6cb9-4bb9-9049-2e897503be0a.png">

**Comment by Pipazoul** [comment]
@aangelot I can add a section in the instanceConf file where it would be possible to define the center position by default
