### ISSUE TITLE
Cursor 

### ISSUE THREAD

**Issue by SeongHunChandra** [datatlas-erasme/front#39]
**Is your feature request related to a problem? Please describe.**
The open hand is confusing in terms of interaction

**Describe the solution you'd like**
Different cursor states, like in Google Maps 
- default state : a black arrow
- clickable point (POI) rollover : a hand with a pointed finger 
- while dragging the map : a 4 arrows cross

**Comment by Pipazoul** [comment]
"while dragging the map : a 4 arrows cross"  will not be possible for now
