### ISSUE TITLE
Get the logo urlfrom the backend API

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#41]
**Is your feature request related to a problem? Please describe.**
The logo displayed on datAtlas are hardcoded, when creating a new instance those also are displayed 

**Describe the solution you'd like**
fetch the logo images from the backend API

**Comment by racine-p-a** [comment]
@Pipazoul new route created for : 
- uploading images
- get a list of all uploaded images

**Comment by racine-p-a** [comment]
@Pipazoul 
Be careful though, if an image is posted with the same name of another one already posted, it will replace it in the folder.
This is intended.
