### ISSUE TITLE
Empty multiselect

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#44]
**Is your feature request related to a problem? Please describe.**
In the drop-down list of a multiselect, the first choice is empty (allowing the user to select POIs without data). But it's a little weird to have an empty first choice

**Describe the solution you'd like**
Is it possible to replace the empty box with a box containing a predetermined text such as "Empty data"?
And why not put this choice at the bottom of the list.

**Comment by lutangar** [comment]
@aangelot  shall we migrate this issue to __https://github.com/datatlas-erasme/datatlas__ ?

**Comment by aangelot** [comment]
It seems that there is a new behavior with the new version: the empty choice is no longer displayed, that's perfect.
