### ISSUE TITLE
back Notion only pass upcoming events

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#54]
**Is your feature request related to a problem? Please describe.**

For the industrie instance a notion database is used to display events on the map 
The map does not need to show the past events

**Describe the solution you'd like**
To have a param on the notion api route to filter past event (based on the current date of the server)
/notion/databaseid?pastevent=false
=> only the current and future event will be passed in the json

/notion/databaseid?pastevent=true or /notion/databaseid
=> all the events are passed in the json

**Comment by racine-p-a** [comment]
[Commit](https://github.com/datatlas-erasme/back/commit/5d6f334abd80eeb34188d70473f709c1cb8e2367)
It you validate this, i let you close this issue.
