### ISSUE TITLE
 Merge about modal with customization options based on instanceConf

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#63]
**Describe the solution you'd like**
merge the About modal feature from industries to dev branch

All the content should be mapped based on the instance Conf json : 
- bg-image-url 
-  Title 
- Subtitle 
- text-left 
-  buttons-right 
-  text-right 
- logos-right

**Comment by racine-p-a** [comment]
@Pipazoul Can you explain this to me with an example ?

**Comment by Pipazoul** [comment]
> @Pipazoul Can you explain this to me with an example ?

Sorry it was no related to the back

**Comment by aangelot** [comment]
@Pipazoul is there a link with #163 ?

**Comment by lutangar** [comment]
Closing in favor of https://github.com/datatlas-erasme/datatlas/issues/249 in the new __Datatlas__ codebase.
