### ISSUE TITLE
Return acf type field

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#67]
The acf field **type** is not returned by the back 

    type : (a mapping is needed between the machine name of the subfields and the human readable name)
        immeuble : Dans mon immeuble
        rue : Dans ma rue
        ecole : Dans mon école
        entreprise : Dans mon entreprise
        chantier : Sur mon chantier

**Comment by Pipazoul** [comment]
@racine-p-a  
The field acf:type could be renamed types_projet ?

**Comment by racine-p-a** [comment]
@Pipazoul done ee78e9b47c4515d03e6d22f0f7e29c2954b283fe
