### ISSUE TITLE
Add missing data on clic and hover

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#69]
The filters **Status** and **Tags** are missing on the canographia front instance for the Projects data layer

**Comment by aangelot** [comment]
Data for filters and modals : 

**Projects** : 
- On hover : titre du projet, tags, adresse 
- On clic : image, titre du projet, adresse, nombre d'arbres plantés, tags, contact (si j'accepte d'être contacté est validé), lien vers la fiche projet Canographia
- Filters : typologie de projets, statut du projet, tags

**Events** : 
- On hover : titre de l'événement, date, adresse
- On clic : image, titre de l'événement, adresse, lien d'inscription, lien vers la fiche événement Canographia
- Filters : no filter (there shouldn't be too many events) 

**Plant trees** : 
- On hover : titre de la plantation, nombre d'arbres plantés, adresse
- On clic : image, titre de la plantation, nombre d'arbres plantés, adresse
- Filters : no filter 

Do not show event if "Date à partir de laquelle archiver l'événement" is overdated. 


Be careful : for events and projects, address is divided in two fields an open one (for the number and street) and a multiselect (for the city)

**Comment by Pipazoul** [comment]
unfortunatly the tags cannot be displayed in the popover because they are declared as as an array

**Comment by Pipazoul** [comment]
@aangelot  " contact (si j'accepte d'être contacté est validé),"
How does this work ? the wordpress API only returns public articles infos, it this handled on the wordpress backoffice ?

**Comment by Pipazoul** [comment]
No inscription url in event returned by back, created an issue https://github.com/datatlas-erasme/back/issues/18

**Comment by Pipazoul** [comment]
Updated , (the title and the inscription links are listed bellow as an issue)

Projects :

- [ ] On hover : titre du projet, tags, adresse
- [ ] On clic : image, titre du projet, adresse, nombre d'arbres plantés, tags, contact (si j'accepte d'être contacté est validé), lien vers la fiche projet Canographia
- [x] Filters : typologie de projets, statut du projet, tags

Events :

- [x]  On hover : titre de l'événement, date, adresse
- [ ] On clic : image, titre de l'événement, adresse, lien d'inscription, lien vers la fiche événement Canographia
- [x]Filters : no filter (there shouldn't be too many events)

Plant trees :
 - [x] On hover : titre de la plantation, nombre d'arbres plantés, adresse
  - [x] On clic : image, titre de la plantation, nombre d'arbres plantés, adresse
 - [x] Filters : no filter

**Comment by Pipazoul** [comment]
@aangelot `Do not show event if "Date à partir de laquelle archiver l'événement" is overdated.`
Is the event still public on wordpress when ist overdated ?
