### ISSUE TITLE
Responsive version for industry

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#74]
**Is your feature request related to a problem? Please describe.**
Industry version is not usable with mobile 

**Describe the solution you'd like**
Create a responsive version inspired by Alimentation version

**Comment by Pipazoul** [comment]
@aangelot  I think the milestone on this issue should be **v0.5.3**, I dont think we will be able to have it done for the begining of september

**Comment by aangelot** [comment]
Design required

**Comment by Pipazoul** [comment]
![4-mobile-MIND7 (5)](https://user-images.githubusercontent.com/8368283/196155781-441a091a-e91d-410a-9f3a-ff2afc29312c.jpg)
![4-mobile-MIND7 (4)](https://user-images.githubusercontent.com/8368283/196155785-9a97e7b0-c4f2-4056-a910-2df906ec32e1.jpg)
![4-mobile-MIND7 (3)](https://user-images.githubusercontent.com/8368283/196155786-e1519606-2340-4368-8a21-5d747b140f6d.jpg)
![4-mobile-MIND7 (2)](https://user-images.githubusercontent.com/8368283/196155789-d2793857-b517-4b8c-ad7e-f73c4547cd84.jpg)
![4-mobile-MIND7 (1)](https://user-images.githubusercontent.com/8368283/196155791-16d1a2fb-c3c5-4cca-834b-d5ded8bb6b16.jpg)
![4-mobile-MIND7](https://user-images.githubusercontent.com/8368283/196155792-8561a6e9-dde7-4c79-b94b-362017f87966.jpg)
![4-mobile-MIND7 (6)](https://user-images.githubusercontent.com/8368283/196155794-320d2db5-782e-4ce7-bfdc-e33db96fa212.jpg)

**Comment by lutangar** [comment]
Will be implemented in the __Datatlas__ codebase.
> See last version of the design in https://github.com/datatlas-erasme/datatlas/issues/247#issue-1810171568
