### ISSUE TITLE
Update the changes of the Project WP Content

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#76]
**Is your feature request related to a problem? Please describe.**
The content structure on the wordpress api has changed, the field adress is not longer used it causes the back to crash on every request

**Describe the solution you'd like**
Update the back for the 'projet' content. Return place_label and place_city (acf fields)
remove the unused adress param
Also the request to https://api-adresse.data.gouv is no longer needed, the lat and long are declared in the acf fields, please use them if possible

**Comment by racine-p-a** [comment]
step 1 : API data gouv no longer called

**Comment by racine-p-a** [comment]
I let you check if this works. If so, close this issue.

**Comment by Pipazoul** [comment]
@racine-p-a The lat and long stil need to be returned, they are available in the acf field => place
![image](https://user-images.githubusercontent.com/8368283/180426851-1c8fb063-afa6-4c6c-a086-c933b722d2d7.png)

**Comment by racine-p-a** [comment]
Done @Pipazoul
