### ISSUE TITLE
Add a new wordpress content type [Arbres Plantes]

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#77]
**Is your feature request related to a problem? Please describe.**
A new content type has been added on wordpress (trees_hotspot)

**Describe the solution you'd like**
when called on route 
api/data/wordpress/canographia.datagora.erasme.org/wp-json/wp/v2/trees_hotspot/

The back should return : 
- titre => title.rendered
- nb_arbres => acf.trees
- img (the first image url)
- lat and long coord (based on the place_address place_zipcode and place_city fields)
- url of the post

**Comment by racine-p-a** [comment]
Should be done.
https://github.com/datatlas-erasme/back/commit/1f0031415f4bc03431635342fd55e1059983f8fc

**Comment by racine-p-a** [comment]
Done now ?
https://github.com/datatlas-erasme/back/tree/6e790e1bbe66a94607229a137706ab5de1a59eb6
@Pipazoul
