### ISSUE TITLE
Integration new design Industry

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#82]
**Describe the solution you'd like**
UX/UI coming soon

**Comment by Pipazoul** [comment]
@SeongHunChandra 
<img width="2866" alt="3-menu-combo" src="https://user-images.githubusercontent.com/8368283/182533704-a6b5ed83-976c-4e74-b9e2-eed95cd18f64.png">

**Comment by Pipazoul** [comment]
@SeongHunChandra  What happends when to subfilters are open at the same time ?
Also Im not really sure about the final result of the search bar, do you have an example of it in use ?

**Comment by Pipazoul** [comment]
@SeongHunChandra  Which font do you use ?

**Comment by SeongHunChandra** [comment]
@Pipazoul 
1. When two subfilters are open, the whole side panel expands accordingly, we may need a scroll bar, I can design one. 
2. Regarding the search results, it depends on the nature of the result :
- if it's a POI, the other elements are hidden/filtered and the interface should zoom / focus on the POI.
- if it's a street or an area > zoom and display only the POI in this street or area
- if it's filter > activate it 
3. In the buttons, large text in lower case is in Roboto Regular, small text in capitals is in Roboto Medium.

**Comment by SeongHunChandra** [comment]
@Pipazoul - I just added a scrollbar to the Filters illustration. 
<img width="2865" alt="1-filtres-principe-2" src="https://user-images.githubusercontent.com/93269688/184884322-60f083eb-e697-410b-914c-0508d06a1578.png">
<img width="3355" alt="2-recherche" src="https://user-images.githubusercontent.com/93269688/184884327-4c8d6f78-dee3-4428-8ed3-61a56f7cf6c5.png">
<img width="2866" alt="3-menu-combo" src="https://user-images.githubusercontent.com/93269688/184884333-5c8d521c-6fe5-449a-8d76-d644f73932b3.png">

**Comment by aangelot** [comment]
Atomize this issue

**Comment by lutangar** [comment]
> See new design in https://github.com/datatlas-erasme/datatlas/issues/247#issue-1810171568 and partial implementation latest implementation done in #248

**Comment by aangelot** [comment]
Good work !!
