### ISSUE TITLE
Add SonarCube for code analysis

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#88]
Cf MAGO requirement : 
Développements spécifiques : le code source doit faire l’objet d’une analyse automatique (à chaque “commit”) de code, via SonarQube.

**Comment by Pipazoul** [comment]
Needs to be implemented on the forge because of licencing usage

**Comment by aangelot** [comment]
Depends on #92

**Comment by lutangar** [comment]
This codebase is not maintained anymore but there is now an official __Github__ integration :
https://docs.sonarsource.com/sonarqube/latest/devops-platform-integration/github-integration/

This integration is enabled in [new __Datatlas__ codebase](https://github.com/datatlas-erasme/datatlas)
