### ISSUE TITLE
Auth for admin front office with OIDC 

### ISSUE THREAD

**Issue by aangelot** [datatlas-erasme/front#89]
Cf MAGO requirement : 
La fédération d’identité doit être réalisée à l’aide du protocole Open ID Connect (OIDC) ou OAuth2 +

**Comment by Pipazoul** [comment]
Is this requirement mandatory ? 
Can be added in a feature wishlist ?

**Comment by lutangar** [comment]
Superceded by https://github.com/datatlas-erasme/datatlas/issues/250
