### ISSUE TITLE
Automatically update docker image when changes are detected

### ISSUE THREAD

**Issue by lutangar** [datatlas-erasme/front#94]
**Is your feature request related to a problem? Please describe.**
Project docker images on public registry are outdated.

**Describe the solution you'd like**
I notice there was a Github action which was doing this job but was deleted  in 06e60d4cdf254f79b245041c1dcbbacf62d9c774 and I wondered why.

Maybe it was because the action was trigger everytime even if there were no changes.
If that so it could be mitigated using a cache strategy.

**Resources**
- https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching

**Comment by Pipazoul** [comment]
This file was removed, only to make the workflow folder cleaner, there still is a build-push docker action [push_docker_master.yml](https://github.com/datatlas-erasme/front/blob/master/.github/workflows/push_docker_master.yml)

This file was never used on master, only on dev branch

Should i use the same file name on each branch but with a different action trigger ? maybe at least for dev and master branch ?

The latest docker-registry images for the front is `datatlas-front `
the images `datatlas-dev` and `datatlas` will be deleted as they are not clear enough

For the docker build layer caching i have added this [issue](https://github.com/datatlas-erasme/front/issues/95)

**Comment by aangelot** [comment]
Closed for #95
